jwt:
  key:
    id: bootiful-key
  persistence:
    password: password
    salt: 626F6F746966756C
logging:
  level:
    root: debug
    web: debug
    dev.hobie.authorization_service: debug
spring:
  codec:
    log-request-details: true
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema/*sql
