spring:
  security:
    oauth2:
      authorizationserver:
        client:
          crm-client:
            require-authorization-consent: true
            registration:
              client-id: crm
              client-secret: "{bcrypt}$2a$10$m7dGi0viwVH63EjwZc6UdeUQxPuiVEEdFbZFI9nMxHAASTOIDlaVO" # <1>
              authorization-grant-types: client_credentials, authorization_code, refresh_token # <2>
              redirect-uris: http://127.0.0.1:8082/login/oauth2/code/spring # <3>
              scopes: user.read,user.write,openid # <4>
              client-authentication-methods: client_secret_basic
