server:
  port: 8082
spring:
  cloud:
    gateway:
      routes:
        - id: resource-service
          uri: http://localhost:8081
          predicates:
            - "Path=/resource-service/**"
          filters:
            - "TokenRelay"
            - "RewritePath=/resource-service/(?<segment>.*), /$\\{segment}"
        - id: default
          uri: http://localhost:8020
          predicates:
            - "Path=/**"
  security:
    oauth2:
      client:
        provider:
          spring:
            issuer-uri: http://localhost:8080
        registration:
          spring:
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            client-id: crm
            client-secret: crm
            provider: spring
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: user.read,openid
logging:
  level:
    root: info
    web: error
    dev.hobie.gatewayservice: error
