logging:
  level:
    root: info
    web: trace
    dev.hobie.processor: debug
spring:
  rabbitmq:
    password: password
    username: user
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:8080
