logging:
  level:
    root: info
    web: trace
    dev.hobie.resourceservice: debug
server:
  port: 8081
spring:
  codec:
    log-request-details: true
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost/postgres
    username: postgres
  rabbitmq:
    password: password
    username: user
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
  sql:
    init:
      mode: always
