logging:
  level:
    root: info
    web: debug
    dev.hobie.resource_service: debug
server:
  port: 8081 # <4>
spring:
  datasource: # <3>
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
  rabbitmq: # <2>
    password: password
    username: user
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080 # <1>
  sql:
    init:
      mode: always
